name: hronom-anchor-java-gen

# Inspired by https://java.testcontainers.org/supported_docker_environment/continuous_integration/dind_patterns/#docker-compose-example
services:
  anchor-java-gen:
    container_name: anchor-java-gen
    build:
      context: .
      target: runner
      secrets:
        - github_username
        - github_token
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: $PWD
    environment:
      EXAMPLE: aaa
    volumes:
      - $PWD:$PWD

secrets:
  github_username:
    file: ./github_username.secret
  github_token:
    file: ./github_token.secret