name: hronom-anchor-java-gen

# Inspired by https://java.testcontainers.org/supported_docker_environment/continuous_integration/dind_patterns/#docker-compose-example
services:
  anchor-java-gen-test:
    container_name: anchor-java-gen-test
    build:
      context: .
      target: runner
      secrets:
        - github_username
        - github_token
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    volumes:
      - .:/work
    # Example command
    command: [
       "--tabLength=2",
       "--sourceDirectory=/work/java-generated",
       "--moduleName=org.your.module",
       "--basePackageName=org.your.package.anchor.gen",
       "--programs=/work/main_net_programs.json",
       "--rpc=https://api.devnet.solana.com",
       "--baseDelayMillis=200",
       "--numThreads=5"
    ]

secrets:
  github_username:
    file: ./github_username.secret
  github_token:
    file: ./github_token.secret